AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
  TaskQueue:
      Type: AWS::SQS::Queue
      Properties:
        VisibilityTimeout: 60
        RedrivePolicy:
          deadLetterTargetArn: !Sub ${DeadLetterQueue.Arn}
          maxReceiveCount: 10
  DeadLetterQueue:
      Type: AWS::SQS::Queue
  ConsumerLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Path: '/'
        Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: sqs
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
              - sqs:ReceiveMessage
              Resource: !Sub ${TaskQueue.Arn}
  ConsumerLambda:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ./consumer
        Handler: consumerLambda
        MemorySize: 128
        Role: !Sub ${ConsumerLambdaRole.Arn}
        Runtime: go1.x
        Timeout: 60
        Environment:
          Variables:
            TASK_QUEUE_URL: !Ref TaskQueue
            #WORKER_LAMBDA_NAME: !Ref WorkerLambda
        Events:
          Timer:
            Type: Schedule
            Properties:
              Schedule: rate(1 minute)